const {
  getAllCompanies,
  signupCompany,
  loginCompany,
  profileData,
  addMainStructure,
  allStructures,
  deleteMainStructure,
  updateMainStructure,
  deletecompany,
  profileDataAbout,
  profileDataSocial,
  profileDataMainStructure,
  profileDataBranches,
  profileDataStaff,
  profileDataOutsource,
  profileDataClients,
  profileDataPic,
  uploadImage,
} = require("./companyController");

const { adminLogin, adminReg, getAdmins } = require("./adminController");

module.exports = {
  getAllCompanies: getAllCompanies,
  signupCompany: signupCompany,
  loginCompany: loginCompany,
  profileData: profileData,
  addMainStructure: addMainStructure,
  adminLogin: adminLogin,
  adminReg: adminReg,
  getAdmins: getAdmins,
  allStructures: allStructures,
  deleteMainStructure: deleteMainStructure,
  updateMainStructure: updateMainStructure,
  deletecompany: deletecompany,
  profileDataAbout: profileDataAbout,
  profileDataSocial: profileDataSocial,
  profileDataMainStructure: profileDataMainStructure,
  profileDataBranches: profileDataBranches,
  profileDataStaff: profileDataStaff,
  profileDataOutsource: profileDataOutsource,
  profileDataClients: profileDataClients,
  profileDataPic: profileDataPic,
  uploadImage: uploadImage,
};
